server:
  port: 8081

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ET2204?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
      username: root
      password: abc123
mybatis:
  mapper-locations: classpath:mappers/*.xml
logging:
  level:
#    com.simons.cn.springbootdemo.dao.system:
    com.etoak.mapper.StudentMapper:
      debug

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
